const GET_DOGS = "GET_DOGS";
const GET_DOG_DETAIL = "GET_DOG_DETAIL";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const CREATE_DOG = "CREATE_DOG";
const DELETE_DOG = "DELETE_DOG";
const FILTER_BY_NAME = "FILTER_BY_NAME";
const IS_CREATED = "IS_CREATED";
const FILTER_BY_WEIGHT = "FILTER_BY_WEIGHT";
const FILTER_BY_TEMP = "FILTER_BY_TEMP";
const SET_PAGE = "SET_PAGE";
const FILTER_BY_ORDER = "FILTER_BY_ORDER";

export {
  GET_DOGS,
  GET_DOG_DETAIL,
  CREATE_DOG,
  DELETE_DOG,
  GET_TEMPERAMENTS,
  FILTER_BY_NAME,
  IS_CREATED,
  FILTER_BY_WEIGHT,
  FILTER_BY_TEMP,
  SET_PAGE,
  FILTER_BY_ORDER
};
